-- 1. Table des paramètres (Nom de la pharmacie, etc.)
CREATE TABLE settings (
key VARCHAR(50) PRIMARY KEY,
value TEXT NOT NULL
);

-- 2. Table des utilisateurs (Pour gérer les accès sans coder les mots de passe en dur)
CREATE TABLE users (
role VARCHAR(20) PRIMARY KEY,
password VARCHAR(255) NOT NULL
);

-- 3. Table des médicaments (Produits)
CREATE TABLE products (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL,
price_sale INT NOT NULL,
price_buy INT DEFAULT 0,
stock_qty INT DEFAULT 0,
min_qty INT DEFAULT 10,
created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Table des ventes
CREATE TABLE sales (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
vendor_role VARCHAR(50),
total_amount INT NOT NULL,
amount_paid INT NOT NULL,
change_returned INT NOT NULL,
sale_date DATE NOT NULL,
sale_time VARCHAR(50) NOT NULL,
created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Table des articles vendus (Détail de chaque vente)
CREATE TABLE sale_items (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
sale_id BIGINT REFERENCES sales(id) ON DELETE CASCADE,
product_id BIGINT REFERENCES products(id),
quantity INT NOT NULL,
price_unit INT NOT NULL
);

-- 6. Table de l'historique des actions (Logs)
CREATE TABLE logs (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
action TEXT NOT NULL,
color VARCHAR(20) DEFAULT 'blue',
created_at VARCHAR(50) NOT NULL
);

-- --- INSERTION DES DONNÉES PAR DÉFAUT ---
INSERT INTO settings (key, value) VALUES ('phn', 'Pharmacie Plus Pro');

INSERT INTO users (role, password) VALUES
('admin', 'admin123'),
('vendor', 'vendeur123'),
('master', 'maitre2024');

INSERT INTO products (name, price_sale, price_buy, stock_qty, min_qty) VALUES
('Paracétamol 500mg', 250, 120, 150, 20),
('Amoxicilline 500mg', 1500, 800, 8, 15),
('Ibuprofène 400mg', 400, 180, 60, 20);